### PR TITLE
BetterShader: don't concat shaders with different versions

### PR DESCRIPTION
**Pull request by brakhane**
I wanted to try your awesome looking pipeline, but it failed on my machine (GTX 880) with the compiler complaining that more than one #version directive was used.

I analysed and fixed the problem and made a slight performance improvement (at least I hope, haven't profiled it).

See the commit message for more info.

### CODE REVIEW

**Comment by heekinho** [comment]
I don't checked the pull request by I vote +1 for the issue. I have a NVIDIA GTX560Ti and the same happens here. I hackd the file to strip the "#version xxx" and just put a "#version 430", but this seems a more elaborate patch.

**Comment by tobspr** [comment]
Thanks for the patch, I really appreciate it! :) I didn't have this issue so far, but I don't have the newest drivers, maybe thats the difference.

**Comment by rdb** [comment]
I hadn't run into this either, curiously.

Then again BetterShader is kind of obsolete today now that its functionality is part of Panda's shader system.  Maybe I'll submit a patch for RenderPipeline to use Panda's new pragmas if I find the time.

**Comment by tobspr** [comment]
Yeah, I also planned to let it use the new pragma system, although I didn't have time for that yet

**Pull request merged**
